language: rust
cache: cargo

rust:
  - stable
  - nightly

script:
  - cargo test --all --release
  - cargo test --all --all-features --release

env:
  - RUSTFLAGS="-D warnings"

matrix:
  allow_failures:
    - name: rustfmt
    - name: clippy
    - rust: nightly
  fast_finish: true
  include:
    - name: "Rust: 1.34.0"
      rust: 1.34.0
      env: {} # clear `-D warnings` above; allow warnings

    # Test `polyval` with the PCLMULQDQ-accelerated backend
    - name: "Rust: 1.34.0 (polyval)"
      rust: 1.34.0
      env: RUSTFLAGS="-Ctarget-cpu=sandybridge -Ctarget-feature=+sse2,+sse4.1"
      script: cd polyval && cargo test --release --tests
    - name: "Rust: stable (polyval)"
      rust: stable
      env: RUSTFLAGS="-Ctarget-cpu=sandybridge -Ctarget-feature=+sse2,+sse4.1"
      script: cd polyval && cargo test --release --tests

    # no_std build
    - name: "Rust: stable (thumbv7em-none-eabihf)"
      rust: stable
      install: rustup target add thumbv7em-none-eabihf
      script: cargo build --all --target thumbv7em-none-eabihf --release
    - name "Rust: nightly (benches)"
      rust: nightly
      script: cargo build --all-features --benches
    - name: rustfmt
      rust: stable
      install: rustup component add rustfmt
      script: cargo fmt --all -- --check
    - name: clippy
      rust: stable
      install: rustup component add clippy
      script: cargo clippy --all

branches:
  only:
    - master
